// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9c4hfH5-00j_oXXi3hbqOB-ndoXT0pE',
    appId: '1:552695007453:web:f7213ec2aa64fdd475f334',
    messagingSenderId: '552695007453',
    projectId: 'quizapp-3d567',
    authDomain: 'quizapp-3d567.firebaseapp.com',
    storageBucket: 'quizapp-3d567.firebasestorage.app',
    measurementId: 'G-XHJZBWHFT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTukDbkLIL3nP2XVYnf91KonVksiiTRxk',
    appId: '1:552695007453:android:ceed5152598759a875f334',
    messagingSenderId: '552695007453',
    projectId: 'quizapp-3d567',
    storageBucket: 'quizapp-3d567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvodDrxDYEygywYhay50fbOww7ZrEgOTw',
    appId: '1:552695007453:ios:1e050b13348c9ce375f334',
    messagingSenderId: '552695007453',
    projectId: 'quizapp-3d567',
    storageBucket: 'quizapp-3d567.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvodDrxDYEygywYhay50fbOww7ZrEgOTw',
    appId: '1:552695007453:ios:1e050b13348c9ce375f334',
    messagingSenderId: '552695007453',
    projectId: 'quizapp-3d567',
    storageBucket: 'quizapp-3d567.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp9c4hfH5-00j_oXXi3hbqOB-ndoXT0pE',
    appId: '1:552695007453:web:df1fd31709035bbc75f334',
    messagingSenderId: '552695007453',
    projectId: 'quizapp-3d567',
    authDomain: 'quizapp-3d567.firebaseapp.com',
    storageBucket: 'quizapp-3d567.firebasestorage.app',
    measurementId: 'G-HY9149YZYR',
  );
}
