// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDalsV7WN6UMXjcnvHCbX3r7Fpx6a_1kmE',
    appId: '1:448733345449:web:95974bd82dea5879411bb8',
    messagingSenderId: '448733345449',
    projectId: 'project-ca3e8',
    authDomain: 'project-ca3e8.firebaseapp.com',
    storageBucket: 'project-ca3e8.firebasestorage.app',
    measurementId: 'G-PZ2VEXGBP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZn8z9tS7NJ30hAdO2tRvp_mpE25-FpgY',
    appId: '1:448733345449:android:e292636925779426411bb8',
    messagingSenderId: '448733345449',
    projectId: 'project-ca3e8',
    storageBucket: 'project-ca3e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxcgNJTS64HktpUdsFZgu0KmAGC9or4nU',
    appId: '1:448733345449:ios:7470020dca772417411bb8',
    messagingSenderId: '448733345449',
    projectId: 'project-ca3e8',
    storageBucket: 'project-ca3e8.firebasestorage.app',
    iosBundleId: 'com.example.projectp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxcgNJTS64HktpUdsFZgu0KmAGC9or4nU',
    appId: '1:448733345449:ios:7470020dca772417411bb8',
    messagingSenderId: '448733345449',
    projectId: 'project-ca3e8',
    storageBucket: 'project-ca3e8.firebasestorage.app',
    iosBundleId: 'com.example.projectp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDalsV7WN6UMXjcnvHCbX3r7Fpx6a_1kmE',
    appId: '1:448733345449:web:fcc055e3769f4171411bb8',
    messagingSenderId: '448733345449',
    projectId: 'project-ca3e8',
    authDomain: 'project-ca3e8.firebaseapp.com',
    storageBucket: 'project-ca3e8.firebasestorage.app',
    measurementId: 'G-8JGD6TK3JL',
  );
}
